version: "2.4"

volumes:
  blockchain:
    name: btc-data
  memmpool_api:
    name: btc-api
  memmpool_indexer:
    name: btc-db
  mempool_blockchain:
    name: mempool-blockchain
  electrs_data:
    name: electrs-data


services:

  node:
    container_name: btc-node
    image: blockcore/bitcoin-angornet:latest
    mem_limit: 2048m
    cpus: 0.8 # how many cpus to use
    healthcheck:
      test: ["CMD", "bitcoin-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.bitcoin
    environment:
      UACOMMENT: $UACOMMENT
      BLOCKPRODUCTIONDELAY: ${BLOCKPRODUCTIONDELAY:-30}
      MINERENABLED: ${MINERENABLED:-0} # change this to 1 if this node needs to mine (however for simplicity there should only be one mining node per challenge)
      NBITS: $NBITS
      SIGNETCHALLENGE: ${SIGNETCHALLENGE:-512102a3f8184701a033e5f8faa295647374b0bbc868082240d6e7ad8e9ecb0d86e6d451ae}
      EXTERNAL_IP: $EXTERNAL_IP
      RPCUSER: ${RPCUSER:-rpcuser}
      RPCPASSWORD: ${RPCPASSWORD:-rpcpassword}
      ADDNODE: ${ADDNODE:-207.180.254.78, 173.249.17.85}
    ports:
      - 18333:18333 # Make this a public node.
      - 8333:8333 # Make this a public node.
      - 38333:38333 # Make this a public node.
      - 38332:38332
    networks:
      - btcnetwork

  mempool_api:
    container_name: mempool-api
    image: blockcore/mempool-backend:latest
    environment:
      MEMPOOL_BACKEND: "electrum"
      ESPLORA_REST_API_URL: "http://mempool-electrs:3003"
      ESPLORA_REQUEST_TIMEOUT: "50000"
      ELECTRUM_HOST: "mempool-electrs"
      ELECTRUM_PORT: "5001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: "node"
      CORE_RPC_PORT: "38333"
      CORE_RPC_USERNAME: "rpcuser"
      CORE_RPC_PASSWORD: "rpcpassword"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: "debug"
      MEMPOOL_INDEXING_BLOCKS_AMOUNT: -1
      ANGOR_ENABLED: "true"
      VIRTUAL_HOST: tbtc.indexer.angor.io
      VIRTUAL_PORT: 8999
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: tbtc.indexer.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:8999
    restart: unless-stopped
    stop_grace_period: 1m
    command: "./wait-for-it.sh mempool_db:3306 --timeout=720 --strict -- ./start.sh"
    ports:
      - 8999:8999
    volumes:
      - memmpool_api:/backend/cache
    networks:
      - btcnetwork
      - proxy

  mempool_db:
    container_name: mempool-db
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.21
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - memmpool_indexer:/var/lib/mysql
    networks:
      - btcnetwork

  mempool_web:
    container_name: "mempool_web"
    environment:
      MAINNET_ENABLED: "false"
      ROOT_NETWORK: "signet"
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool_api"
      LIGHTNING: "false"
      ANGOR_ENABLED: "true"
      VIRTUAL_HOST: test.explorer.angor.io
      VIRTUAL_PORT: 8080
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: test.explorer.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:8080
    image: blockcore/mempool-frontend:latest
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for mempool_db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "8080:8080"
    networks:
      - btcnetwork
      - proxy

  mempool_electrs:
    container_name: mempool-electrs
    image: mempool/electrs:latest
    user: root
    ports:
      - 5001:5001
      - 3003:3003
    depends_on:
      node:
        condition: service_healthy
    entrypoint:
      /bin/electrs
    command: |
      --network signet
      --jsonrpc-import
      --daemon-rpc-addr btc-node:38332
      --cookie "rpcuser:rpcpassword"
      --db-dir /electrs
      --http-addr 0.0.0.0:3003
      --electrum-rpc-addr 0.0.0.0:5001
      -vvvv
    volumes:
      - electrs_data:/electrs
    networks:
      - btcnetwork

networks:
  btcnetwork:
    external: false
    name: btcnetwork
  proxy:
    external: true
    name: proxy
